### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by hvasbath** [williamjameshandley/spherical_kde#3]
https://github.com/williamjameshandley/spherical_kde/blob/917788be453ea65a718dc9e977b16ed8f8ff90fc/spherical_kde/distributions.py#L42

This explodes in memory usage for large arrays.
Could you please suggest a way to loop this to avoid out of memory? I do not fully understand what tensordot does. Thanks a lot!

**Comment by williamjameshandley** [comment]
Could you provide a minimal working example, to give us an understanding of the scale of the memory problem?

**Comment by hvasbath** [comment]
So this explodes my laptop with 8GB RAM.

```
from spherical_kde.distributions import VonMisesFisher_distribution as vmfd
from spherical_kde.utils import polar_from_decra
import numpy as num


grid_size = (300, 300)

lats_vec = num.linspace(-90., 90, grid_size[0])
lons_vec = num.linspace(-180., 180, grid_size[1])

lons, lats = num.meshgrid(lons_vec, lats_vec)
phi, theta = polar_from_decra(lons, lats)

phi0 = num.mod(num.random.normal(0., scale=0.1, size=5000), 2. * num.pi)
theta0 = num.random.normal(0., scale=0.1, size=5000)

out = vmfd(
    phi=phi, theta=theta,
    phi0=phi0, theta0=theta0, sigma0=1)
```

**Comment by hvasbath** [comment]
Any comments on that?

**Comment by hvasbath** [comment]
Its not the issue of the tensordot, but rather after that. With logsum exp. I will do batch processing and loop over that.
You are right you have to return such a large array and cannot reduce it in any way at this stage. Needs to be taken care after that for the kde.
Thanks!

**Comment by williamjameshandley** [comment]
Many thanks for resolving this @hvasbath, and apologies for my delay in replying -- The start of term is always pretty busy.
